version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: danny
      POSTGRES_PASSWORD: 7980@dan
      POSTGRES_DB: foodrecipe
    volumes:
      - db_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://danny:7980@dan@postgres:5432/foodrecipe
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: 7980@hasura

  golang:
    build:
      context: /backend/
      dockerfile: Dockerfile
    depends_on:
      - hasura
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - .:/app
    environment:
      HASURA_URL: http://hasura:8080/v1/graphql
      environment:
      DB_CONNECTION_STRING: postgres://danny:7980@dan@postgres:5432/foodrecipe
      JWT_SECRET: 7980@jwt
    command: ["go", "run", "main.go"]


volumes:
  db_data:
